# Copyright Aberic Person. All Rights Reserved.
#
# Is licensed under the: GNU General Public License v2.0
#

version: '2'

services:

  edge:
    container_name: edge
    image: aberic/fabric-edge
    environment:
      - USERNAME=admin
      - PASSWORD=password
    command: bash /home/init-edge.sh
    ports:
      - 8080:8080