# Copyright Aberic Person. All Rights Reserved.
#
# Is licensed under the: GNU General Public License v2.0
#

version: '2'

services:

  sdk:
    container_name: sdk
    image: aberic/fabric-sdk
    environment:
      # 组织相关配置
      - ORG_NAME=Org1
      - ORG_TLS=true
      - ORG_CA_TLS=false
      - ORG_USERNAME=Admin
      - ORG_CRYPTO_CONFIG_DIR=/home/config/crypto-config
      - ORG_CHANNEL_ARTIFACTS_DIR=/home/config/channel-artifacts
      - ORG_CA_NAME=ca
      - ORG_CA_LOCATION=http://118.89.243.236:7054
      - ORG_MSP_ID=Org1MSP
      - ORG_DOMAIN_NAME=org1.example.com
      - ORG_ORDERER_DOMAIN_NAME=example.com
      - ORG_CHANNEL_NAME=mychannel
      - ORG_CHAINCODE_NAME=test2cc
      - ORG_CHAINCODE_SOURCE=/code
      - ORG_CHAINCODE_PATH=chaincode/chaincode_example02
      - ORG_CHAINCODE_VERSION=1.2
      - ORG_PROPOSAL_WAIT_TIME=90000
      - ORG_INVOKE_WAIT_TIME=120
      # 排序服务相关配置
      - ORDERER_NAME=orderer.example.com
      - ORDERER_LOCATION=grpc://118.89.243.236:7050
      # 节点服务相关配置
      - PEER_NAME=peer0.org1.example.com
      - PEER_EVENT_HUB_NAME=peer0.org1.example.com
      - PEER_LOCATION=grpc://118.89.243.236:7051
      - PEER_EVENT_HUB_LOCATION=grpc://118.89.243.236:7053
      - PEER_IS_EVENT_LISTENER=true
    volumes:
      - /home/jar/config/:/home/config/
    command: bash /home/init.sh
    ports:
      - 8080:8080