# Copyright Aberic Person. All Rights Reserved.
#
# Is licensed under the: GNU General Public License v2.0
#

version: '2'

services:

  sdk:
    container_name: sdk
    image: aberic/fabric-sdk
    volumes:
      - /home/jar/config/:/home/config/
    command: bash /home/init.sh
    ports:
      - 8080:8080