server:
  port: 8080
  #address: localhost

spring:
  datasource:
    url: jdbc:sqlite:/Users/Aberic/Documents/code/github/fabric.sqlite
    username:
    password:
    driver-class-name: org.sqlite.JDBC

